# Generated by Django 3.1.3 on 2020-12-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoloSinging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phoneNum', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='content',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
