# Generated by Django 3.1.3 on 2020-12-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20201213_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotographyWorkshops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('phoneNum', models.CharField(blank=True, max_length=10)),
                ('whatsapp', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('interest', models.CharField(choices=[(1, 'Basics of Photography'), (2, 'Light Painting Workshop'), (3, 'Portrait Workshop')], max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='photography',
            name='type1',
        ),
        migrations.RemoveField(
            model_name='photography',
            name='type2',
        ),
        migrations.AddField(
            model_name='photography',
            name='photo',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='photography',
            name='video',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
