# Generated by Django 3.1.3 on 2020-12-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20201215_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('phoneNum', models.CharField(blank=True, max_length=10)),
                ('whatsapp', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='photographyworkshops',
            name='interest',
        ),
        migrations.AddField(
            model_name='beatboxing',
            name='idlink',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='classicaldance',
            name='idlink',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='monoact',
            name='idlink',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='photographyworkshops',
            name='basicsofphoto',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='photographyworkshops',
            name='lightpainting',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='photographyworkshops',
            name='portrait',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='poetry',
            name='idlink',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='rapbattle',
            name='idlink',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='shortfilms',
            name='idlink',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='solosinging',
            name='idlink',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='westerndance',
            name='idlink',
            field=models.URLField(blank=True),
        ),
    ]
