# Generated by Django 3.1.3 on 2020-12-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20201215_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solosinging',
            name='phoneNum',
            field=models.BigIntegerField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='solosinging',
            name='whatsapp',
            field=models.BigIntegerField(blank=True, max_length=10),
        ),
    ]
