# Generated by Django 3.1.3 on 2020-12-16 16:16

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20201216_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solosinging',
            name='email',
            field=models.EmailField(blank=True, help_text='Email ID', max_length=200),
        ),
        migrations.AlterField(
            model_name='solosinging',
            name='idlink',
            field=models.URLField(blank=True, help_text='Link your ID'),
        ),
        migrations.AlterField(
            model_name='solosinging',
            name='phoneNum',
            field=phone_field.models.PhoneField(blank=True, help_text='Phone Number', max_length=31),
        ),
        migrations.AlterField(
            model_name='solosinging',
            name='whatsapp',
            field=phone_field.models.PhoneField(blank=True, help_text='Whatsapp Number', max_length=31),
        ),
    ]
