# Generated by Django 3.1.3 on 2020-12-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20201216_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solosinging',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='solosinging',
            name='idlink',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='solosinging',
            name='phoneNum',
            field=models.PositiveBigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='solosinging',
            name='whatsapp',
            field=models.PositiveBigIntegerField(blank=True),
        ),
    ]
