# Generated by Django 3.1.3 on 2020-12-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20201217_2138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photography',
            new_name='PhotographyContest',
        ),
    ]
