# Generated by Django 3.1.3 on 2020-12-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20201218_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupsinging',
            old_name='name',
            new_name='name_of_group',
        ),
        migrations.RemoveField(
            model_name='groupsinging',
            name='age',
        ),
        migrations.AddField(
            model_name='groupsinging',
            name='name_of_head',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='groupsinging',
            name='number_of_members',
            field=models.IntegerField(blank=True, default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupsinging',
            name='phoneNum',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
