# Generated by Django 3.1.3 on 2020-12-19 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20201219_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beatboxing',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator, django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='beatboxing',
            name='phoneNum',
            field=models.PositiveBigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='beatboxing',
            name='whatsapp',
            field=models.PositiveBigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='classicaldance',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator, django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='monoact',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator, django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='monoact',
            name='phoneNum',
            field=models.PositiveBigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='monoact',
            name='whatsapp',
            field=models.PositiveBigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator, django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='phoneNum',
            field=models.PositiveBigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='whatsapp',
            field=models.PositiveBigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='rapbattle',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator, django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='rapbattle',
            name='phoneNum',
            field=models.PositiveBigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='rapbattle',
            name='whatsapp',
            field=models.PositiveBigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='solosinging',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator, django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='westerndance',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator, django.core.validators.MaxValueValidator(25)]),
        ),
    ]
