# Generated by Django 3.1.3 on 2020-12-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20201219_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rules',
            field=models.TextField(blank=True, max_length=100000000000000000000),
        ),
    ]
