# Generated by Django 3.1.3 on 2020-12-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20201219_1931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Videography',
        ),
        migrations.AddField(
            model_name='event',
            name='youtube',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='photographyworkshops',
            name='basicsofphoto',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='photographyworkshops',
            name='lightpainting',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='photographyworkshops',
            name='portrait',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tazhakhabar',
            name='day',
            field=models.CharField(choices=[('1', 'Day 1 - Topic 1'), ('2', 'Day 2 - Topic 2')], max_length=200),
        ),
    ]
