# Generated by Django 3.1.3 on 2020-12-20 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20201220_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('phoneNum', models.CharField(blank=True, max_length=10)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('age', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(25)])),
                ('city', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('howplay', models.CharField(choices=[(1, 'Solo'), (2, 'In a pair'), (3, 'In a group of 3')], max_length=200)),
                ('groupname', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GlamUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('phoneNum', models.CharField(blank=True, max_length=10)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('age', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(21)])),
                ('city', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('idlink', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
            ],
        ),
    ]
