# Generated by Django 3.1.3 on 2020-12-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_charades_glamup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='youtube',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
