# Generated by Django 3.1.3 on 2020-11-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='img',
            field=models.ImageField(blank=True, upload_to='corepics'),
        ),
    ]
