# Generated by Django 3.1.3 on 2020-12-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenteventisland',
            name='eventslug',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
